<#
.SYNOPSIS
  Report pending UI-string translations in include/localized_strings.h and,
  optionally, emit a ready-to-fill TSV template.

.DESCRIPTION
  English (DEFAULT_LOCALIZED_UI_STRINGS) is the canonical set of UI string IDs.
  For each requested language table (<LANG>_LOCALIZED_UI_STRINGS) this reports:
    * MISSING          - an English ID absent from that language (falls back to
                         English at runtime, per utils.cpp GetLocalizedString).
    * ENGLISH-VALUED   - present, but its value is byte-identical to English
                         (may be a real gap, or legitimately identical such as
                         "OK", "Web", ">", "'?", or a word already correct in
                         the target language -- judge per entry).
  HELP_CONTENT_ID is excluded (it is generated by sync_help_content.ps1).

  With -OutTemplate, writes a TSV (LANG<TAB>ID<TAB>ENGLISH_SOURCE) of the
  reported entries so you can translate the 3rd column in place and feed it to
  apply_translations.ps1. Escape sequences (\n, \0) are kept literal.

.PARAMETER Languages
  Comma-separated section names (e.g. "GERMAN,ITALIAN") or "all" (default: all
  languages except DEFAULT/English).

.PARAMETER Mode
  Which buckets to report/emit: "missing" (default), "english", or "both".

.PARAMETER OutTemplate
  Optional path to write a TSV template pre-filled with the English source.

.PARAMETER Header
  Path to localized_strings.h (default: ..\include\localized_strings.h relative
  to this script).

.EXAMPLE
  powershell -File scripts/find_pending_translations.ps1

.EXAMPLE
  powershell -File scripts/find_pending_translations.ps1 -Languages GERMAN,ITALIAN -Mode both -OutTemplate pending.tsv
#>
param(
  [string]$Languages = 'all',
  [ValidateSet('missing', 'english', 'both')][string]$Mode = 'missing',
  [string]$OutTemplate,
  [string]$Header
)
$ErrorActionPreference = 'Stop'
if (-not $Header) { $Header = Join-Path $PSScriptRoot '..\include\localized_strings.h' }

# --- parse localized_strings.h into ordered sections -----------------------
$lines = [System.IO.File]::ReadAllLines($Header, [System.Text.Encoding]::UTF8)
$secRe = [regex]'\b([A-Z_]+)_LOCALIZED_UI_STRINGS\s*='
$idRe  = [regex]'^\s*\{\s*([A-Z0-9_]+_ID)\s*,'
$slRe  = [regex]'^\s*\{\s*([A-Z0-9_]+_ID)\s*,\s*L"(.*)"\s*\}\s*,?\s*$'

$sections = @()
for ($i = 0; $i -lt $lines.Count; $i++) {
  $m = $secRe.Match($lines[$i])
  if ($m.Success) { $sections += [pscustomobject]@{ Name = $m.Groups[1].Value; Start = $i } }
}
for ($s = 0; $s -lt $sections.Count; $s++) {
  $start = $sections[$s].Start
  $end   = if ($s -lt $sections.Count - 1) { $sections[$s + 1].Start } else { $lines.Count }
  $ids = New-Object System.Collections.Generic.HashSet[string]
  $val = @{}
  $inRaw = $false
  for ($i = $start; $i -lt $end; $i++) {
    $ln = $lines[$i]
    if ($inRaw) { if ($ln -match '\)HELP"') { $inRaw = $false }; continue }
    if ($ln -match 'LR"HELP\(') { if ($ln -notmatch '\)HELP"') { $inRaw = $true }; continue }
    $a = $idRe.Match($ln); if ($a.Success) { [void]$ids.Add($a.Groups[1].Value) }
    $b = $slRe.Match($ln); if ($b.Success) { $val[$b.Groups[1].Value] = $b.Groups[2].Value }
  }
  $sections[$s] | Add-Member NoteProperty Ids $ids
  $sections[$s] | Add-Member NoteProperty Val $val
}

$eng = $sections | Where-Object { $_.Name -eq 'DEFAULT' }
if (-not $eng) { throw "DEFAULT_LOCALIZED_UI_STRINGS not found in $Header" }
$engVal = $eng.Val
$canon  = @($eng.Ids) | Where-Object { $_ -ne 'HELP_CONTENT_ID' }

# --- select target languages ------------------------------------------------
if ($Languages -eq 'all') {
  $targets = $sections | Where-Object { $_.Name -ne 'DEFAULT' } | ForEach-Object { $_.Name }
}
else {
  $targets = $Languages.ToUpper() -split '\s*,\s*' | Where-Object { $_ }
}

$tsv = New-Object System.Collections.Generic.List[string]
"{0,-20} {1,8} {2,10}" -f 'Language', 'Missing', 'EngValued'
"{0,-20} {1,8} {2,10}" -f '--------', '-------', '---------'
foreach ($name in $targets) {
  $sec = $sections | Where-Object { $_.Name -eq $name }
  if (-not $sec) { Write-Warning "Unknown language section: $name"; continue }
  $missing   = @($canon | Where-Object { -not $sec.Ids.Contains($_) })
  $identical = @($canon | Where-Object { $sec.Ids.Contains($_) -and $engVal.ContainsKey($_) -and $sec.Val.ContainsKey($_) -and $sec.Val[$_] -eq $engVal[$_] })
  "{0,-20} {1,8} {2,10}" -f $name, $missing.Count, $identical.Count

  $emit = @()
  if ($Mode -eq 'missing' -or $Mode -eq 'both') { $emit += $missing }
  if ($Mode -eq 'english' -or $Mode -eq 'both') { $emit += $identical }
  foreach ($id in $emit) {
    $src = if ($engVal.ContainsKey($id)) { $engVal[$id] } else { '<<MULTILINE - copy from English by hand>>' }
    $tsv.Add(("{0}`t{1}`t{2}" -f $name, $id, $src))
  }
}

if ($OutTemplate) {
  $head = @(
    '# Translation template - fill the 3rd column (VALUE) with translations.',
    '# Format: LANG<TAB>ID<TAB>VALUE   (keep \n and \0 literal; UTF-8).',
    '# Then: powershell -File scripts/apply_translations.ps1 -Tsv <this file>'
  )
  $all = $head + $tsv
  [System.IO.File]::WriteAllLines($OutTemplate, $all, (New-Object System.Text.UTF8Encoding($false)))
  ""
  "Wrote $($tsv.Count) rows to $OutTemplate"
}
