#pragma once

#ifndef resource_h
#define resource_h


#ifndef IDC_STATIC
#define IDC_STATIC              -1
#endif

#define IDI_SIMONSAYS           101
#define IDR_MAINMENU            102
#define IDD_ABOUTBOX            103
#define IDD_SETTINGS_DIALOG      104
#define IDR_MAINACCEL           105
#define ID_FILE_EXIT            1001
#define ID_HELP_ABOUT           1002
#define ID_SETTINGS_OPEN        1003
#define ID_TRAY_SHOW            2001
#define ID_TRAY_EXIT            2002
#define IDC_EDIT_PHRASE         3001
#define IDC_BUTTON_PLAY         3002
#define IDC_BUTTON_CATEGORIES   3003
#define IDC_SETTINGS_DEFAULT_TEXT      4001
#define IDC_SETTINGS_USE_DEFAULT_TEXT  4002
#define IDC_SETTINGS_VOICE_COMBO       4003
#define IDC_SETTINGS_VOLUME_EDIT       4004
#define IDC_SETTINGS_RATE_EDIT         4005
#define IDC_SETTINGS_LANGUAGE_COMBO    4006
#define IDC_SETTINGS_VOLUME_SLIDER     4007
#define IDC_SETTINGS_RATE_SLIDER       4008
#define IDC_SETTINGS_TEST_VOICE        4009
#define IDC_SETTINGS_SPEAK_ON_CLICK            4010
#define IDC_SETTINGS_REMEMBER_CATEGORY_WINDOW  4011
#define IDC_SETTINGS_MINIMIZE_CATEGORY_WINDOW  4012
#define IDC_SETTINGS_INCREASE_VOLUME_WHEN_PLAYING 4013
#define IDC_SETTINGS_REDUCE_OTHER_AUDIO_WHEN_PLAYING 4014

#endif // resource_h
